package com.coderchessansh.dyslexiaassist;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.speech.tts.TextToSpeech;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
  LinearLayout root, content; TextToSpeech tts; float scale=1f; int purple=Color.rgb(108,99,255);
  int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
  TextView tv(String s,float size,int color){ TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setPadding(dp(8),dp(6),dp(8),dp(6));return v; }
  Button btn(String s){ Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b; }
  @Override public void onCreate(Bundle b){super.onCreate(b); tts=new TextToSpeech(this,st->{}); showHome();}
  void base(){ root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(247,247,251));
    LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(16),dp(10),dp(16),dp(8));
    ImageView logo=new ImageView(this);logo.setImageResource(com.coderchessansh.dyslexiaassist.R.drawable.ic_logo);bar.addView(logo,new LinearLayout.LayoutParams(dp(42),dp(42)));
    TextView title=tv("DyslexiaAssist",21,Color.rgb(35,35,50));title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);bar.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));
    root.addView(bar); content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(4),dp(18),dp(18));root.addView(content,new LinearLayout.LayoutParams(-1,0,1));setContentView(root); }
  void showHome(){base(); TextView h=tv("Read with less stress.",28,Color.rgb(35,35,50));h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);content.addView(tv("Simple reading tools designed to make text easier to follow.",16,Color.DKGRAY));
    Button read=btn("📖  Easy Reader");Button practice=btn("🧩  Word Practice");Button settings=btn("⚙  Reading Settings");content.addView(read);content.addView(practice);content.addView(settings);read.setOnClickListener(v->reader());practice.setOnClickListener(v->practice());settings.setOnClickListener(v->settings());
    TextView note=tv("DyslexiaAssist is a learning support tool, not a diagnostic or medical device.",13,Color.GRAY);note.setPadding(8,dp(20),8,8);content.addView(note); }
  void reader(){base(); TextView h=tv("Easy Reader",25,Color.rgb(35,35,50));h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h); EditText input=new EditText(this);input.setHint("Paste or type text here…");input.setGravity(Gravity.TOP);input.setMinHeight(dp(180));input.setTextSize(19*scale);content.addView(input,new LinearLayout.LayoutParams(-1,dp(210)));Button speak=btn("🔊 Read aloud");Button clear=btn("Clear");Button back=btn("← Home");content.addView(speak);content.addView(clear);content.addView(back);speak.setOnClickListener(v->tts.speak(input.getText().toString(),TextToSpeech.QUEUE_FLUSH,null,"reader"));clear.setOnClickListener(v->input.setText(""));back.setOnClickListener(v->showHome()); }
  void practice(){base();TextView h=tv("Word Practice",25,Color.rgb(35,35,50));h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);content.addView(tv("Read the word, then choose what you hear.",16,Color.DKGRAY));String[] words={"apple","window","school","friend","planet"};for(String w:words){Button x=btn("🔊  "+w);x.setOnClickListener(v->tts.speak(w,TextToSpeech.QUEUE_FLUSH,null,"word"));content.addView(x);}Button back=btn("← Home");content.addView(back);back.setOnClickListener(v->showHome()); }
  void settings(){base();TextView h=tv("Reading Settings",25,Color.rgb(35,35,50));h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);content.addView(tv("Adjust the text size for comfortable reading.",16,Color.DKGRAY));SeekBar seek=new SeekBar(this);seek.setMax(100);seek.setProgress((int)((scale-0.8f)/1.0f*100));content.addView(seek);TextView preview=tv("Preview: Reading should feel comfortable and clear.",20,Color.rgb(35,35,50));content.addView(preview);seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){scale=.8f+p/100f;preview.setTextSize(20*scale);}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});Button back=btn("← Home");content.addView(back);back.setOnClickListener(v->showHome()); }
  @Override protected void onDestroy(){if(tts!=null)tts.shutdown();super.onDestroy();}
}